fold 0
Model: "functional_1"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 2772, 6, 3)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d (Conv2D)                 │ (None, 2768, 1, 64)    │         5,824 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lambda (Lambda)                 │ (None, 2768, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ [(None, 2768, 64),     │        33,024 │
│                                 │ (None, 64), (None,     │               │
│                                 │ 64)]                   │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ self_attention (SelfAttention)  │ [(None, 1024), (None,  │         2,560 │
│                                 │ 16, 2768)]             │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 2)              │         2,050 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 43,458 (169.76 KB)
 Trainable params: 43,458 (169.76 KB)
 Non-trainable params: 0 (0.00 B)
Traceback (most recent call last):
  File "/home/rezvank/.local/lib/python3.11/site-packages/pydot/core.py", line 1753, in create
    stdout_data, stderr_data, process = call_graphviz(
                                        ^^^^^^^^^^^^^^
  File "/home/rezvank/.local/lib/python3.11/site-packages/pydot/core.py", line 133, in call_graphviz
    process = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2023/x86-64-v3/Compiler/gcccore/python/3.11.5/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rezvank/.local/lib/python3.11/site-packages/keras/src/utils/model_visualization.py", line 37, in check_graphviz
    pydot.Dot.create(pydot.Dot())
  File "/home/rezvank/.local/lib/python3.11/site-packages/pydot/core.py", line 1762, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lustre06/project/6003138/rezvank/5_model/baseline.py", line 121, in <module>
    fold_model = model(input_shape= X.shape[1:], num_labels = NUM_LABELS, LSTM_units = LSTM_UNITS, \
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6003138/rezvank/5_model/baseline.py", line 42, in model
    plot_model(model, to_file=SAVE_DIR / str(NAME+'_model.png'), show_shapes=True, show_layer_names=True)
  File "/home/rezvank/.local/lib/python3.11/site-packages/keras/src/utils/model_visualization.py", line 416, in plot_model
    if not check_graphviz():
           ^^^^^^^^^^^^^^^^
  File "/home/rezvank/.local/lib/python3.11/site-packages/keras/src/utils/model_visualization.py", line 39, in check_graphviz
    except (OSError, pydot.InvocationException):
                     ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pydot' has no attribute 'InvocationException'
